AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'test/samples/**/*'
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
