sudo: false
language: ruby

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9.0.5.0
  - rbx-3

env:
  # this doesn't do anything for MRI or RBX, but it doesn't hurt them either
  # for JRuby, it enables us to get more accurate coverage data
  - JRUBY_OPTS="--debug"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
    - rvm: rbx-3
  fast_finish: true

before_install: gem update bundler
script: bundle exec rake
